export const TRANSACTION_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    REVERSED: "REVERSED",
};

export const TRANSACTION_TYPE = {
    TRANSFER: "TRANSFER",
    DEPOSIT: "DEPOSIT",
    WITHDRAWAL: "WITHDRAWAL",
    PAYMENT: "PAYMENT",
    REFUND: "REFUND",
};